# Generated by Django 3.2.7 on 2021-10-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent_code', models.CharField(max_length=10)),
                ('continent_name', models.CharField(max_length=100)),
                ('no_of_countries', models.IntegerField()),
                ('highest_point', models.CharField(max_length=100)),
                ('areainkm2', models.IntegerField()),
                ('areainsqmi', models.IntegerField()),
                ('population', models.IntegerField()),
            ],
            options={
                'db_table': 'continent_master',
            },
        ),
    ]
