# Generated by Django 3.2.7 on 2021-10-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_continent_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continent',
            name='population',
            field=models.FloatField(),
        ),
    ]
