# Generated by Django 3.2.7 on 2021-10-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_alter_continent_population'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continent',
            name='areainkm2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='continent',
            name='areainsqmi',
            field=models.FloatField(),
        ),
    ]
