# Generated by Django 3.2.7 on 2021-10-23 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_auto_20211023_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(default='', max_length=10)),
                ('country_name', models.CharField(max_length=256)),
                ('capital_city', models.CharField(max_length=256)),
                ('flag', models.ImageField(upload_to='flag')),
                ('symbol', models.ImageField(upload_to='symbol')),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.continent')),
            ],
        ),
    ]
