# Generated by Django 3.2.7 on 2021-10-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BharatRatna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Laureates', models.CharField(max_length=256)),
                ('Image', models.ImageField(upload_to='photos')),
                ('Year', models.CharField(max_length=50)),
                ('StateOrCountry', models.CharField(max_length=100)),
                ('PrimeMinister', models.CharField(max_length=100)),
                ('PartyInPower', models.CharField(max_length=256)),
                ('Notes', models.TextField()),
            ],
            options={
                'db_table': 'bharat_ratna_winners',
            },
        ),
        migrations.CreateModel(
            name='Nobel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256)),
                ('Image', models.ImageField(upload_to='pics')),
                ('Received_on', models.CharField(max_length=100)),
                ('Date_of_birth', models.CharField(max_length=100)),
                ('Birth_place', models.CharField(max_length=256)),
                ('Residence', models.CharField(max_length=256)),
                ('Motivation', models.TextField()),
                ('Language', models.CharField(max_length=100)),
                ('Prize_share', models.CharField(max_length=100)),
                ('Life', models.TextField()),
                ('Work', models.TextField()),
                ('Category_id', models.IntegerField()),
                ('Created_by', models.CharField(max_length=100)),
                ('Created_on', models.DateField()),
            ],
            options={
                'db_table': 'nobel_prize_winners',
            },
        ),
        migrations.CreateModel(
            name='StudentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(max_length=100)),
                ('Gender', models.CharField(choices=[(0, 'Female'), (1, 'Male'), (2, 'Others')], max_length=20)),
                ('Password', models.CharField(max_length=50)),
                ('BranchName', models.CharField(choices=[(0, 'Select Branch'), (1, 'Civil'), (2, 'EEE'), (3, 'MECH'), (4, 'ECE'), (5, 'CSE')], default=0, max_length=10)),
                ('DateOfBirth', models.DateField(max_length=50)),
                ('StudentUrl', models.URLField(max_length=128)),
            ],
            options={
                'db_table': 'student_details',
            },
        ),
    ]
