# Generated by Django 3.2.7 on 2021-10-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nobel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentform',
            name='Grading',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='studentform',
            name='Gender',
            field=models.BooleanField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Others')], max_length=20),
        ),
    ]
